cart/urls.py
from django.urls import path
from . import views


urlpatterns = [ 
     path("", views.cart, name="cart"),
     path("add_cart",views.add_cart,name="add_cart"),
     path("checkout" ,views.checkout , name="checkout"),
     path("quantity_edit" ,views.quantity_edit , name="quantity_edit"),
    #  path("decrement_cart/<int:id>", views.decrement_cart , name ="decrement_cart"),
     path("delete_cart", views.delete_cart, name="delete_cart"),
     path("quantity_minus", views.quantity_minus, name="quantity_minus"),
     path("Gusr", views.Gusr, name="Gusr"),
     path("cartrefresh",views.cartrefresh,name="cartrefresh")
     
               
]

category/urls.py
from django.urls import path
from . import views


app_name = 'category'

urlpatterns = [ 
        path("add_product",views.add_product,name="add_product"),       
        path("dropdown_P",views.dropdown_P,name="dropdown_P"),  
        path("dropdown_PE",views.dropdown_PE,name="dropdown_PE"),     
        path("add_category",views.add_category,name="add_category"),
        path("add_subcategory",views.add_subcategory,name="add_subcategory"),
        path("edit_category/<int:id>",views.edit_category,name="edit_category"),
       
        path("delete_category",views.delete_category,name="delete_category"),
        path("delete_subcategory",views.delete_subcategory,name="delete_subcategory"),
        path("delete_product",views.delete_product,name="delete_product"),
               
]

dwell/urls.py
import statistics
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from accounts.views import*
from django.conf.urls.static import static

urlpatterns = [
    path('admintop/', admin.site.urls),
    path('', include("accounts.urls")),
    path('', include("pages.urls")),
    path('cart/', include("cart.urls")),
    path('category/', include("category.urls")), 
    path('orders/', include("orders.urls")),
    path('wishlist/', include("wishlist.urls")),
    path('user_profile/', include("user_profile.urls")),
    path('user_profile/offer', include("offer.urls")),
    path('user_profile/coupen', include("coupen.urls")),
    path('user_profile/wallet', include("wallet.urls")),
    path('variations/', include("variation.urls")),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = "accounts.views.page_not_found_view"
handler500 = "accounts.views.error_500"

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [ 
     path("",views.index,name="index"),
     path("shop",views.shop,name="shop"),
     path("signle_P/<int:id>", views.signle_P,name="signle_P"),
     path("mensSC/<int:id>",views.mensSC,name="mensSC"),
     path("MshirtsP/<int:id>",views.MshirtsP,name="MshirtsP"),
     path("c_category",views.c_category,name="c_category"),
     path("productsingle",views.productsingle,name="productsingle"),
     path("about",views.about,name="about"),
     path("blog",views.blog,name="blog"),
     path("contact",views.contact,name="contact"),
     path("a_tables", views.a_tables, name="a_tables"),
     path("category", views.category, name="category"),
     path("subcategory", views.subcategory, name="subcategory"),
     path("product", views.product, name="product"),
     path("add_category", views.add_category, name="add_category"),
     path("add_subcategory", views.add_subcategory, name="add_subcategory"),
     path("add_product", views.add_product, name="add_product"),
     path("edit_subcategory/<int:id>", views.edit_subcategory, name="edit_subcategory"),
     path("edit_product/<int:id>",views.edit_product,name="edit_product"),
     path("user_block",views.user_block, name="user_block"),

               
]

wallet/urls.py
from django.urls import path
from . import views




urlpatterns = [ 
        path("",views.wallet,name="wallet"),  


    ]

cart/models.py
from django.db import models
from category.models import *
from accounts.models import Account
from variation.models import Variation
# Create your models here.

class GCart(models.Model):
    Guest_id         = models.CharField(max_length = 250, blank=True)
    date_added      = models.DateTimeField(auto_now_add = True)
    
    def __str__(self):
        return self.Guest_id
    
class CartItem(models.Model):
    user            = models.ForeignKey(Account, on_delete=models.CASCADE ,null =True)
    product         = models.ForeignKey(Products, on_delete = models.CASCADE)
    Guest           = models.ForeignKey(GCart, on_delete = models.CASCADE, null =True)
    Quantity        = models.IntegerField()
    varient_id      = models.CharField(max_length=100,null=True,blank=True,default=0)
    varient_price   = models.IntegerField(null= True , blank = True ,default=0)
    is_active       = models.BooleanField(default=True)
    
    def sub_total(self):
        if self.product.offer_price is not None and self.product.offer_price is not 0:
            return self.product.offer_price *self.Quantity
        # elif self.varient_price is not 0:
        #     return self.varient_price *self.Quantity
        else:
            return self.product.selling_price *self.Quantity
    def sub_total_c(self,coupen_didected):
        if self.product.offer_price is not None and self.product.offer_price is not 0:
            if coupen_didected is not 0:
                return self.product.offer_price *self.Quantity-coupen_didected 
            else:
                return self.product.offer_price *self.Quantity
        else:
            return self.product.selling_price *self.Quantity
    def color_find(self):
        if self.varient_id is not '0':
            varient = Variation.objects.get(variation_id=self.varient_id)
            return varient.color
    def size_find(self):
        if self.varient_id is not '0':
            varient = Variation.objects.get(variation_id=self.varient_id)
            return varient.size
    def __str__(self):
        return self.product
    
class OldCart(models.Model):
    user            = models.ForeignKey(Account, on_delete=models.CASCADE ,null =True)
    product         = models.ForeignKey(Products, on_delete = models.CASCADE)
    Quantity        = models.IntegerField()
    date_added      = models.DateField(auto_now_add = True ,null = True)
    
    def __str__(self):
        return self.user

wallet/models.py
from django.db import models
from accounts.models import Account
# Create your models here.


class Wallet(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.FloatField(null=False, default=0)
    added_at = models.DateTimeField(auto_now_add=True)
    

cart/views.py
import ast
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from category.models import Products
from accounts.models import Address
from django.http import JsonResponse
import razorpay
from django.conf import settings
from . models import GCart, CartItem
from django.contrib import messages
from bunch import bunchify
from munch import DefaultMunch
from variation.models import Variation
from django.views.decorators.cache import never_cache


def create(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart


def add_cart(request):
    user = request.user
    id = request.GET.get('id')
    varient = 0
    v_id_ = 0
    product = Products.objects.get(id=id)
    if request.GET.get('color') and request.GET.get('size'):
        color = request.GET.get('color')
        size = request.GET.get('size')
        if color is not '0' and size is not '0':
            varient  = Variation.objects.get(product=product,color=color,size=size)
            v_id_ = varient.variation_id

    if user.is_authenticated:
        try:
            if varient is not 0:
                cart_item = CartItem.objects.get(product=product,user=user,varient_id=v_id_)
                if cart_item.varient_id == v_id_:
                    cart_item.Quantity +=1
                    cart_item.save()
                    status = True
                    return JsonResponse({"status":status})
                else:
                                        
                    cart_item = CartItem.objects.create(product=product, Quantity = 1, user= user ,varient_id=varient.variation_id ,varient_price=varient.price)
                    cart_item.save()
                    status = False
                    return JsonResponse({"status":status})
            else:
                cart_item = CartItem.objects.get(product=product,user=user,varient_id=0)
                
                cart_item.Quantity +=1
                cart_item.save()
                status = True
                return JsonResponse({"status":status})
                

        except CartItem.DoesNotExist:
            if varient is not 0:
                cart_item = CartItem.objects.create(product=product, Quantity = 1, user= user ,varient_id=varient.variation_id ,varient_price=varient.price)
                cart_item.save()
                status = False
                return JsonResponse({"status":status})
            else:
                cart_item = CartItem.objects.create(product=product, Quantity = 1, user= user)
                cart_item.save()
                status = False
                return JsonResponse({"status":status})
                

    else: 
        try:
            G_id=GCart.objects.get(Guest_id = create(request))
            
            if varient is not 0:
                if CartItem.objects.filter(product=product,Guest =G_id,varient_id = v_id_).exists():
                    cart_item = CartItem.objects.get(product=product,Guest =G_id,varient_id = v_id_)
                    if cart_item.varient_id == v_id_:
                        cart_item.Quantity +=1
                        cart_item.save()
                        status = True
                    
                    return JsonResponse({"status":status})
                else:
                                        
                    cart_item = CartItem.objects.create(product=product, Quantity = 1, Guest = G_id ,varient_id=varient.variation_id ,varient_price=varient.price)
                    cart_item.save()
                    status = False
                    
                    return JsonResponse({"status":status})
            else:
                try:
                    cart_item = CartItem.objects.get(product=product,Guest =G_id,varient_id=0)
                
                    cart_item.Quantity +=1
                    cart_item.save()
                    status = True

                    return JsonResponse({"status":status})
                except:
                    cart_item = CartItem.objects.create(product=product, Quantity = 1, Guest = G_id)
                    cart_item.save()
                    status = False
                    return JsonResponse({"status":status})
                

        except GCart.DoesNotExist:
            G_id=GCart.objects.create(Guest_id= create(request))
            G_id.save()
            if varient is not 0:
                cart_item = CartItem.objects.create(product=product, Quantity = 1, Guest = G_id ,varient_id=varient.variation_id ,varient_price=varient.price)
                cart_item.save()
                status = False
                return JsonResponse({"status":status})
            else:
                cart_item = CartItem.objects.create(product=product, Quantity = 1, Guest = G_id)
                cart_item.save()
                status = False
                return JsonResponse({"status":status})
        
        return redirect("cart")

def cart(request,Gcart=0, total=0,quantity=0,cart_items=None,tax=0,delv=0,g_total=0,count=0):

    
    try :
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user,is_active=True)
        
        count = CartItem.objects.filter(user =request.user).count()

        for cart_item in cart_items:
            c_varient = cart_item.varient_id
            if c_varient != "0":
                v = Variation.objects.get(variation_id=cart_item.varient_id)
                v_price = v.price
                cart_item.varient_price=v_price
                cart_item.save()
                
            if cart_item.product.offer_price is not None and cart_item.product.offer_price is not 0:
                total += (cart_item.product.offer_price * cart_item.Quantity)
            else:
                total += (cart_item.product.selling_price * cart_item.Quantity)
            quantity += cart_item.Quantity
            tax = (5*total)/100
            delv = 5
            g_total = total+ tax+delv

    except :
        
        if GCart.objects.filter(Guest_id=create(request)).exists():
            id=GCart.objects.get(Guest_id=create(request))
            cart_items=CartItem.objects.filter(Guest=id,is_active=True)
            
            for cart_item in cart_items:
                c_varient = cart_item.varient_id
                if c_varient != "0":
                    v = Variation.objects.get(variation_id=cart_item.varient_id)
                    v_price = v.price
                    cart_item.varient_price=v_price
                    cart_item.save()
                
                if cart_item.product.offer_price is not None and cart_item.product.offer_price is not 0:
                    total += (cart_item.product.offer_price * cart_item.Quantity)
                else:
                    total += (cart_item.product.selling_price * cart_item.Quantity)
                quantity += cart_item.Quantity
                tax = (5*total)/100
                delv = 5
                g_total = total+ tax+delv
        cart=request.session.session_key
        if GCart.objects.filter(Guest_id=cart).exists():
            id=GCart.objects.get(Guest_id=cart)
            count=CartItem.objects.filter(Guest=id,is_active=True).count()
                
    return render (request,"cart.html", {
        "total":total,
        "quantity":quantity,
        "cart_items":cart_items,
        "delv":delv,
        "tax":tax,
        "g_total":g_total,
        "count":count
    })
    
def cartrefresh(request,Gcart=0, total=0,quantity=0,cart_items=None,tax=0,delv=0,g_total=0):
    try :
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user,is_active=True)
            
        for cart_item in cart_items:
            c_varient = cart_item.varient_id
            if c_varient != "0":
                v = Variation.objects.get(variation_id=cart_item.varient_id)
                v_price = v.price
                cart_item.varient_price=v_price
                cart_item.save()
                
            if cart_item.product.offer_price is not None and cart_item.product.offer_price is not 0:
                total += (cart_item.product.offer_price * cart_item.Quantity)
            else:
                total += (cart_item.product.selling_price * cart_item.Quantity)
            quantity += cart_item.Quantity
            tax = (5*total)/100
            delv = 5
            g_total = total+ tax+delv

    except :
        
        if GCart.objects.filter(Guest_id=create(request)).exists():
            id=GCart.objects.get(Guest_id=create(request))
            cart_items=CartItem.objects.filter(Guest=id,is_active=True)
            
            for cart_item in cart_items:
                c_varient = cart_item.varient_id
                if c_varient != "0":
                    v = Variation.objects.get(variation_id=cart_item.varient_id)
                    v_price = v.price
                    cart_item.varient_price=v_price
                    cart_item.save()
                
                if cart_item.product.offer_price is not None and cart_item.product.offer_price is not 0:
                    total += (cart_item.product.offer_price * cart_item.Quantity)
                else:
                    total += (cart_item.product.selling_price * cart_item.Quantity)
                quantity += cart_item.Quantity
                tax = (5*total)/100
                delv = 5
                g_total = total+ tax+delv
                
    return render (request,"cartitems.html", {
        "total":total,
        "quantity":quantity,
        "cart_items":cart_items,
        "delv":delv,
        "tax":tax,
        "g_total":g_total
    })
    
def delete_cart(request):
    id = request.GET.get('id')
    v_id = request.GET.get('v_id')
    product=get_object_or_404(Products,id=id)
    if request.user.is_authenticated:

wallet/views.py
from django.shortcuts import render
from .models import Wallet

# Create your views here.
def wallet(request):
    user = request.user
    wallet = Wallet.objects.get(user_id=user)
    
    return render(request, "wallet.html",{"wallet":wallet})

wishlist/views.py
from django.shortcuts import render
from django.http import JsonResponse
from accounts.models import Wishlist
from category.models import Products


def add_to_wishlist(request):
    id = request.GET.get('id')
    wished_item = Products.objects.get(id=id)
    checkwish = Wishlist.objects.filter(wished_item=wished_item , user = request.user).exists()
    if checkwish is True:
        return 
    else:
        wishlist = Wishlist.objects.create(wished_item=wished_item, user=request.user ,quantity = 1)
        return JsonResponse({"id":id})

def wishlist(request):
    try:
        wish = Wishlist.objects.filter(user=request.user).order_by('-added_date')
        return render(request, "wishlist.html", {'wish':wish})
    except:
        wish = None
        return render(request, "wishlist.html", {'wish': wish})

def delete_wish(request):
    id = request.GET.get("id")
    wish = Wishlist.objects.get(id=id)
    res = None
    wish.delete()
    return JsonResponse({"res":res})

templates/base.html
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>Dwell| Ecommerce &amp; Shopping</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "assets/img/favicons/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "assets/img/favicons/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "assets/img/favicons/favicon-16x16.png" %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "assets/img/favicons/favicon.ico" %}">
    <link rel="manifest" href="{% static "assets/img/favicons/manifest.json" %}">
    <meta name="msapplication-TileImage" content="assets/img/favicons/mstile-150x150.png">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="{% static "assets/css/theme.css" %}" rel="stylesheet"  />


  </head>
  

  <body>



    {% block content %}


    
    {% endblock %}






    <!--    JavaScripts-->
<!-- ===============================================-->
<script src="{% static "vendors/@popperjs/popper.min.js" %}"></script>
<script src="{% static "vendors/bootstrap/bootstrap.min.js" %}"></script>
<script src="{% static "vendors/is/is.min.js" %}"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
<script src="{% static "vendors/feather-icons/feather.min.js" %}"></script>
<script>
  feather.replace();
</script>
<script src="{% static "assets/js/theme.js" %}"></script>
<!-- ===============================================-->
<link href="https://fonts.googleapis.com/css2?family=Jost:wght@200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">
</body>

</html>

templates/cartitems.html
    <div class="col-lg-8 col-sm-12 col-xs-12">
      <div class="p-5">
        <div class="d-flex justify-content-between align-items-center mb-5">
          <h6 class="fw-bold mb-0 text-black">Items</h6>
          <h6 class="fw-bold mb-0 text-black">name</h6>
          <h6 class="fw-bold mb-0 text-black">quantitiy</h6>
          <h6 class="fw-bold mb-0 text-black">total</h6>
          <h6 class="mb-0 text-muted">remove</h6>
        </div>

        <div id ="cartitem">
        {% for i in cart_items  %}
        <hr class="my-4">
        <div class="row mb-4 d-flex justify-content-between align-items-center">
          <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2">
            <img
              src="/media/{{i.product.product_img1}}"
              class="img-fluid rounded-3" alt="Cotton T-shirt">
          </div>
          <div class="col-sm-3 col-md-3 col-lg-3 col-xl-3">
            <h6 class="text-muted">{{i.product.subcategory}}</h6>
            <h6 class="text-black mb-0">{{i.product.product_name}}</h6>
            
            {% if i.varient_id != "0" %}
            
            <h6 class="text-black mb-0">Color : {{i.color_find}}</h6>
            <h6 class="text-black mb-0">Size : {{i.size_find}}</h6>
            {% endif %}
              
          </div>
<div class="col-sm-3 col-md-3 col-lg-3 col-xl-2 d-flex">
          <a  class="btn btn-link px-2" id='minusbtn{{ forloop.counter }}' onclick= qtyminus("qty{{ forloop.counter }}","{{i.product.id}}","sub_t{{ forloop.counter }}",'minusbtn{{ forloop.counter }}',"{{i.varient_id}}")>-</a> 
                <input id="qty{{ forloop.counter }}"  min="1" max="30" name="quantity" value="{{i.Quantity}}" type="number"
              class="form-control form-control-sm" />
         <a  class="btn btn-link px-2" onclick=idcc("qty{{ forloop.counter }}","{{i.product.id}}","sub_t{{ forloop.counter }}","{{i.varient_id}}")>+</a> 
          </div>
          <div id="sub_t{{ forloop.counter }}" class="col-sm-3 col-md-3 col-lg-2 col-xl-2 offset-lg-1" style="margin: 1rem ;">
            <h6 class="mb-0"  >₹ {{i.sub_total}}  </h6>
          </div>
          <div class="col-sm-4 col-md-4 col-lg-1 col-xl-1 text-end">
            <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a> <button type="button" onclick=deltcart("{{i.product.id}}","{{i.varient_id}}") class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter{{i.id}}">x</button>
          </div>
        </div>
        <!-- Modal -->
            <!-- <div class="modal fade" id="exampleModalCenter{{i.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLongTitle">Are you sure you want to remove from cart ?</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body justify-content-center">
                        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 " style="align-items:center ;">
                            <div class="row justify-content-center align-items-center">
            
                            <img style="align-items:center ; justify-content:center;"
                              src="/media/{{i.product.product_img1}}"
                              class="img-fluid rounded-3" alt="Cotton T-shirt"></div>
                          </div>
                         {{i.product.product_name}}
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                      <a href="" type="button" class="btn btn-primary btn-lg">Yes</a>
                    </div>
                  </div>
                </div>
              </div> -->
              {% endfor %}
            </div>

        <hr class="my-4">

        <div class="pt-5">
          <h6 class="mb-0"><a href="#!" class="text-body"><i
                class="fas fa-long-arrow-alt-left me-2"></i>Back to shop</a></h6>
        </div>
      </div>
    </div>
    <div class="col-lg-4 bg-grey">
      <div class="p-5">
        <h3 class="fw-bold mb-5 mt-2 pt-1">Summary</h3>
        <hr class="my-4">

        <div class="d-flex justify-content-between mb-4">
          <h5 class="text-uppercase">Total</h5>
          <h5 id="total_c">₹ {{total}}</h5>
        </div>

        <h5 class="text-uppercase mb-3">Shipping</h5>

        <div class="mb-4 pb-2">
          <select class="select">
            <option value="1">Standard-Delivery- ₹5.00</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
            <option value="4">Four</option>
          </select>
        </div>

        <h5 class="text-uppercase mb-3">Give code</h5>

        <div class="mb-5">
          <div class="form-outline">
            <input type="text" id="form3Examplea2" class="form-control form-control-lg" />
            <label class="form-label" for="form3Examplea2">Enter your code</label>
          </div>
        </div>
        <div class="d-flex justify-content-between mb-4">

            <h6>Tax :</h6>
            <h5 id="tax_c">₹ {{tax}} +</h5>

        </div>
        <div class="d-flex justify-content-between mb-4">

        
            <h6>Delivery charge :</h6>
            <h5>₹ {{delv}} +</h5>
        </div>
        <hr class="my-4">

        <div class="d-flex justify-content-between mb-5">
          <h5 class="text-uppercase">Total price</h5>
          <h5 id="total_g" class="text-success">₹ {{g_total}}</h5>
        </div>
        
        <a href="{% url 'checkout' %}" type="button" style="color:white;" class="btn btn-dark btn-block btn-lg"
          data-mdb-ripple-color="dark">Buy Now</a>

      </div>
    </div>
  

templates/order_status.html
{% extends 'shop.html' %}

{% load static %}
{% block content %}

	<style>
		.qty .count {
			color: #000;
			display: inline-block;
			vertical-align: top;
			font-size: 25px;
			font-weight: 700;
			line-height: 30px;
			padding: 0 2px
			;min-width: 35px;
			text-align: center;
		}
		.qty .plus {
			cursor: pointer;
			display: inline-block;
			vertical-align: top;
			color: white;
			width: 30px;
			height: 30px;
			font: 30px/1 Arial,sans-serif;
			text-align: center;
			border-radius: 50%;
			}
		.qty .minus {
			cursor: pointer;
			display: inline-block;
			vertical-align: top;
			color: white;
			width: 30px;
			height: 30px;
			font: 30px/1 Arial,sans-serif;
			text-align: center;
			border-radius: 50%;
			background-clip: padding-box;
		}
		div {
			text-align: center;
		}
		.minus:hover{
			background-color: #717fe0 !important;
		}
		.plus:hover{
			background-color: #717fe0 !important;
		}
		/*Prevent text selection*/
		span{
			-webkit-user-select: none;
			-moz-user-select: none;
			-ms-user-select: none;
		}
		input{  
			border: 0;
			width: 2%;
		}
		nput::-webkit-outer-spin-button,
		input::-webkit-inner-spin-button {
			-webkit-appearance: none;
			margin: 0;
		}
		input:disabled{
			background-color:white;
		}
				 
	</style>
 
    <!-- END nav -->
		
		






    <section class="h-100 h-custom">
        <div class="container h-100 py-5">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
      {% if orders is not None %}
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col" class="h5">Product</th>
                      <th scope="col" class="h5">name</th>
                      <th scope="col">Quantity</th>
                      <th scope="col">Price</th>
                      <th scope="col">status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for i in orders  %}
                      
                    
                    <tr>
                      <th scope="row">
                        <div class="d-flex align-items-center">
                          <img src="/media/{{i.product.product_img1}}" class="img-fluid rounded-3"
                            style="width: 120px;" alt="Book">
							<div class="flex-column ms-4">
								
								
							  </div>
                        </div>
                      </th>
					  <td class="align-middle">
                        <p class="mb-0" style="font-weight: 500;">{{i.product.product_name}}</p>
						<p class="mb-0">{{i.product.subcategory}}</p>
                      </td>
                   
                      <td class="align-middle">
                        <p class="mb-0" style="font-weight: 500;">{{i.quantity}}</p>
                      </td>
                      <td class="align-middle">
                        <p class="mb-0" style="font-weight: 500;">₹{{i.total_price}}</p>
                      </td>
                      </td>
                      <td class="align-middle">
                      
                        <p class="mb-0" style="font-weight: 500; color:green;">Order {{i.status}}</p>
                      
                      </td>
                      <td class="align-middle">
                        <a href={% url 'order_details' i.id %} class="btn btn-secondary">View</a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              {% else %}

              <h2>you have no orders yet</h2>
              <a href="{% url "pages:c_category" %}" class="btn btn-secondary " href=""> Shop Now</a>

      
              {% endif %}
            </div>
          </div>
        </div>
      </section>












































   

  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
  <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
  <script src="{% static "js/jquery.stellar.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
  <script src="{% static "js/bootstrap-datepicker.js" %}"></script>
  <script src="{% static "js/scrollax.min.js" %}"></script>


    {% endblock %}